name: news_cli
description: A dart CLI to use newsapi.org API's
version: 0.0.1
homepage: https://github.com/rshrc/news_cli
author: rshrc <rishieric91@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
